### ISSUE TITLE
feat: Login/Signup zustand, auth persistence

### ISSUE THREAD

**Issue by ayeooong** [Perfitt-11-supreme/11-supreme#110]
### 📃Description
> 로그인 회원가입 로직 갈아엎기

### 📌Todo
- [x] 로그인한 사용자 이름 반영
- [x] 로그인 지속성
- [x] 회원가입 중간에 이탈하면 저장 안 되게
- [x] 유효성 검사 방식 수정

### 📝ETC
> x
