### ISSUE TITLE
refactor: login/signup

### ISSUE THREAD

**Issue by ayeooong** [Perfitt-11-supreme/11-supreme#132]
### 📃Description
> 로그인/회원가입 관련 세부사항 수정

### 📌Todo
- [ ] 회원가입 모달로 올라오게?
- [ ] 회원가입하면 로그인 따로 안 하게
- [ ] 챗봇 사용자 이름 반영
- [ ] 회원가입 인증 했는데 데이터 없는 경우 오류 메시지 개선

### 📝ETC
> x
