### ISSUE TITLE
 refactor: 성능 개선

### ISSUE THREAD

**Issue by deswaq1220** [Perfitt-11-supreme/11-supreme#174]
### 📃Description
> 전체적인 성능 개선

### 📌Todo
- [ ] 이미지 태그 alt 누락 추가
- [ ] 이미지 너비, 높이 지정 안되어있는곳 추가
- [ ] css 높이값 수정 

### 📝ETC
> 없음
