### ISSUE TITLE
Refactor-Text/ImageSearch--Style-OnBoading---jobeomjun

### ISSUE THREAD

**Issue by JoBeomJun-FrontEnd** [Perfitt-11-supreme/11-supreme#176]
### 📃Description
> 텍스트/이미지 검색 리팩토링 / 온보딩 CSS오류 수정

### 📌Todo
- [x] 텍스트 검색 문자열 배열 저장시 JSON문자열로 저장
- [x] 이미지 검색시 이미지 혹은 비디오 base64로 바꾸는 함수 중복 코드 함수로 뺴서 같은 코드에 사용
- [x] 온보딩 CSS오류 수정

### 📝ETC
> 없습니다
